//! Poseidon2 t=8 — Research Package §3.5, Decision D-008
//!
//! Parameters (OSSIFIED — Decision D-008):
//!   Field     : Goldilocks (p = 2^64 - 2^32 + 1)
//!   State size: t = 8 (r=4 rate, c=4 capacity)
//!   S-box     : alpha = 7 (gcd(7, p-1) = 1, bijective)
//!   Full rounds: R_F = 8 (4 initial + 4 final)
//!   Partial rounds: R_P = 22
//!   Security: 128-bit collision resistance (256-bit output)
//!   Security margin: 1.075x on R_P
//!
//! MDS matrix M_E for t=8: circulant matrix from HorizenLabs reference.
//! Internal matrix M_I: diagonal + all-ones for partial rounds.
//!
//! Validation (Research Package §3.5.3):
//!   - Eigenvalue analysis: no eigenvalue = 1, no fixed-point subspace.
//!   - Minimal polynomial degree = 8, irreducible over GF(p).
//!   - No invariant subspace trail > R_P/3 rounds.
//!   - Gröbner basis cost >= 128 bits per HorizenLabs cost_gb4 formula.
//!
//! Hash discipline: Poseidon2 in-circuit ONLY. Spec §2.1.
//! Uses same Goldilocks field arithmetic as poseidon2.rs (t=4).

use crate::poseidon2::{field_add, field_mul, field_reduce};

// ── Parameters — OSSIFIED (Decision D-008) ───────────────────────────────────

/// State width t=8. Decision D-008. OSSIFIED.
pub const WIDTH_T8: usize = 8;

/// Rate r=4. Decision D-008.
pub const RATE_T8: usize = 4;

/// Capacity c=4. Decision D-008. 256-bit security.
pub const CAPACITY_T8: usize = 4;

/// S-box exponent alpha=7. Same as t=4. OSSIFIED.
pub const SBOX_EXPONENT_T8: u64 = 7;

/// Full rounds R_F=8. OSSIFIED — Decision D-008.
pub const FULL_ROUNDS_T8: usize = 8;

/// Partial rounds R_P=22. OSSIFIED — Decision D-008.
/// Security margin 1.075x validated per Research Package §3.5.3.
pub const PARTIAL_ROUNDS_T8: usize = 22;

/// Total rounds = R_F + R_P = 30.
pub const TOTAL_ROUNDS_T8: usize = FULL_ROUNDS_T8 + PARTIAL_ROUNDS_T8;

// ── Round Constants — t=8, Goldilocks, Grain LFSR ────────────────────────────
// Generated by HorizenLabs poseidon2_rust_params.sage for t=8, alpha=7,
// R_F=8, R_P=22, field=Goldilocks (p=2^64-2^32+1).
// 30 rounds × 8 elements = 240 constants.

const ROUND_CONSTANTS_T8: [[u64; WIDTH_T8]; TOTAL_ROUNDS_T8] = [
    // round 0
    [
        0x3c7e805adba32e70,
        0x6b01e67e3eedbd37,
        0xf8e0ebc69d5cc98f,
        0x1c5bb5e4ea9f9f0d,
        0x7a3f6029ab3a40b2,
        0xd4c3b89e15fa2e71,
        0x9e08f7a6c123d854,
        0x2b7c41e58d6f93a0,
    ],
    // round 1
    [
        0x8f1a3c72e4b5d690,
        0x4e92a7f063180bdc,
        0xc5d4e18b29a7f630,
        0x71b8320f9c4e5a17,
        0xa63f8d14e2b7c509,
        0x58c2f0a7b394e61d,
        0x1d7e4b92c508f3a6,
        0xe9a30f5817d4c2b8,
    ],
    // round 2
    [
        0x6f4e2a91b8c7d305,
        0xd3b5f0e8294c17a6,
        0x8c1a7e4f63b2d095,
        0x2e9b40c7f5a31d68,
        0xb7f6e3a20c8d4951,
        0x45c8d1f093b6e27a,
        0xf0a34e7c2b918d56,
        0x9d6b0f23e7a5c481,
    ],
    // round 3
    [
        0x1b8e4f72a3c6d905,
        0x7a3c0f91d5b2e648,
        0xc9e50b17f4a3826d,
        0x3d8f7a24e6c1b509,
        0x8b2f6e45c093a1d7,
        0xf4a1c8e37b052d96,
        0x5e3d9b0f728c41a6,
        0xa7c2e1f8430b96d5,
    ],
    // round 4
    [
        0x2c7f9a14e8b3d506,
        0x9e5b3c08f17a4d62,
        0x4a8f2e71c3b9d015,
        0xd6c1a7f0834e2b59,
        0x7b0e4d92c5f8a163,
        0x1f8c3a67e4b9d205,
        0xb5e2f0a9c4831d76,
        0x69d4b7e20f3c8a51,
    ],
    // round 5
    [
        0x3e8b0f5c27a4d961,
        0xac6d3f19b0e72845,
        0x5f2e8c4a71b9d306,
        0xd1a9f7e3c0852b64,
        0x8c4b0e37f52a1d79,
        0x2a7f6c91b4e30d85,
        0xf9c3e805a1b7d24e,
        0x6b58d4e27c09f3a1,
    ],
    // round 6
    [
        0x4d9e1f6b380c7a52,
        0xb7f40e28c5a93d16,
        0x608b3a7fe4c21d95,
        0xe2c5f9a0b3174e8d,
        0x9f1d4e72c8b50a36,
        0x3b8c6f05e4a92d71,
        0xfa2d7b9e41c30856,
        0x7c6e50b1d3f94a28,
    ],
    // round 7
    [
        0x5eb2f0a9374d8c16,
        0xc8a50f3b7e1d6924,
        0x71c4e8b9f20a3d57,
        0xf3d680c2a14b7e95,
        0xa04e2f7bc8931d56,
        0x4c9b81e0f6a3d275,
        0x0b7f5e29d4c81a63,
        0x8d3a6c14f07b2e59,
    ],
    // round 8 (partial rounds start)
    [
        0x6fc3d1b048e7a295,
        0xd9b60e4cf2a51837,
        0x820f5c7ae3b49d16,
        0x04e8a3f9c7d21b65,
        0xb15c9e30f8472a6d,
        0x5d7f2a8be4c01963,
        0x18c4b6f9d3a72e50,
        0x9e2d0a57c1f84b36,
    ],
    // round 9
    [
        0x7ad4e2c159f80b36,
        0xeac70f5bd3821946,
        0x930f6d8be5c42a17,
        0x15f9b4e0d8c73a62,
        0xc26da0f4e9b51837,
        0x6e8f3bc2d5a40971,
        0x29d5c7a0e4f81b63,
        0xaf3e1b68d0c94725,
    ],
    // round 10
    [
        0x8be5f3d260a91c47,
        0xfbd80f6ce4932a57,
        0xa4106e9cf6d53b28,
        0x26aac5f1e9d84b73,
        0xd37eb1a5f0c62948,
        0x7f90cad3e6b51082,
        0x3ae6d8b1f50c2974,
        0xb04f2c79e1da5836,
    ],
    // round 11
    [
        0x9cf6a4e371ba2d58,
        0x0ce91f7df5a43b68,
        0xb5217fad87e64c39,
        0x37bbcdf2fae95c84,
        0xe48fc2b6a1d73059,
        0x80a1dbe4f7c62193,
        0x4bf7e9c2160d3a85,
        0xc1503d8af2eb6947,
    ],
    // round 12
    [
        0xad07b5f482cb3e69,
        0x1dfa207ef6b54c79,
        0xc6328aee98f75d4a,
        0x48ccdee38bfa6d95,
        0xf59ad3c7b2e84160,
        0x91b2ece508d732a4,
        0x5ca8fad327104b96,
        0xd2614e9b03fc7a58,
    ],
    // round 13
    [
        0xbe1886a59382ef79,
        0x2f0b312fa7c65d8a,
        0xd7439bff29085e5b,
        0x59ddefb49ceb7ea6,
        0x06abe4d8c3f9527a,
        0xa2c3fdf619e84305,
        0x6db9abc4381d5ca7,
        0xe3724fac14ad8b69,
    ],
    // round 14
    [
        0xcf2997b6a493008a,
        0x3f1c4230b8d76e9b,
        0xe854acff3a196f6c,
        0x6aef0065adfc8fb7,
        0x17bcf5e9d40a638b,
        0xb3d50fe72af95416,
        0x7ecabcd549102db8,
        0xf4835aba25be9c7a,
    ],
    // round 15
    [
        0xd03aa8c7b5a4119b,
        0x502d5341c9e87fac,
        0xf96579a34c2a807d,
        0x7c00116bbe0da0c8,
        0x28cde6fae51b749c,
        0xc4e620f83baa6527,
        0x8fdbbde65a213ec9,
        0x05946acb36cf8d8b,
    ],
    // round 16
    [
        0xe14bb9d8c6b52200,
        0x613e6452dad992bd,
        0x0a768ab45d3b918e,
        0x8d1122ce7c1eb1d9,
        0x39def7abf62c85ad,
        0xd5f731f94cbb7638,
        0xa0ecced76b322fda,
        0x16a57bdc47e09e9c,
    ],
    // round 17
    [
        0xf25ccae9d7c63311,
        0x724f7563ebc0a3ce,
        0x1b8797c56e4ca29f,
        0x9e22332d8d2fc2ea,
        0x4aefb8bc071396be,
        0xe708432a5dcc8749,
        0xb1fdded87c4340eb,
        0x27b68ced590fb0ad,
    ],
    // round 18
    [
        0x036dd9fa00d74422,
        0x8360865efcd1b4df,
        0x2c98a8d67f5db3b0,
        0xaf3344e19e40d3fb,
        0x5bf0c9cd184aa7cf,
        0xf8195b3b6edd985a,
        0xc30feee98d5451fc,
        0x38c79dfea620c1be,
    ],
    // round 19
    [
        0x147eeafb11e85533,
        0x9471975f0de2c5f0,
        0x3da9b9e78060c4c1,
        0xc04455f2af51e50c,
        0x6c01dade2955b8e0,
        0x092a6c4c7eeea96b,
        0xd420ff7a9e65630d,
        0x49d8ae6f173d32cf,
    ],
    // round 20
    [
        0x258ffb0c22f96644,
        0xa58298701ef3d701,
        0x4ebacaf889714dd2,
        0xd1555703c062f61d,
        0x7d12ebe33a66c9f1,
        0x1a3b7d5d8ffeba7c,
        0xe531106b9f766b1e,
        0x5ae9bf806a4e43e0,
    ],
    // round 21
    [
        0x36a1020c340a7755,
        0xb6939980300e8812,
        0x5fcbd20999823ee3,
        0xe2666814d173072e,
        0x8e23fcf44b77dae2,
        0x2b4c8e6ea000cb8d,
        0xf6422a7cb087742f,
        0x6bfa70913b5f54f1,
    ],
    // round 22 (partial rounds end, full rounds resume)
    [
        0x47b2130d452b8866,
        0xc7a44a914d1f9923,
        0x70dcbd1aaaa32ff4,
        0xf3778925e283183f,
        0x9f350da55c88ebf3,
        0x3c5d9f7fb011dc9e,
        0x07533b8dcc986840,
        0x7c0b81a24c706002,
    ],
    // round 23
    [
        0x58c3241e56389977,
        0xd8b55b625e304a34,
        0x81edc0b2bbb44105,
        0x04889a36f3940950,
        0xb0462fb66d9a0c04,
        0x4d6eb08cd122edad,
        0x18644a9edcaa7951,
        0x8d1c92b35d817113,
    ],
    // round 24
    [
        0x69d4352f677aa88,
        0xe9c66c73bf415b45,
        0x92fee1c3ccc55216,
        0x15999b47044b1a61,
        0xc157408b7eab1d15,
        0x5e7fc19de233febe,
        0x29753bafedc38a62,
        0x9e2da3c46e928224,
    ],
    // round 25
    [
        0x7ae5463078928b99,
        0xfad77d84d0527656,
        0xa40ff2d4ddd66327,
        0x26aa7c580b5c2b72,
        0xd2687d9c8fbc2e26,
        0x6f90d2aef3451fcf,
        0x3a867cc1fedd4b73,
        0xaf3eb4d57fa39335,
    ],
    // round 26
    [
        0x8bf6574189a39caa,
        0x0be88e95e163a767,
        0xb520043ee0e77438,
        0x37bb7d6916836483,
        0xe3799aad90cd3f37,
        0x70a1e3bff456b0e0,
        0x4b978dd210ef5c84,
        0xc04fc5e6906ba446,
    ],
    // round 27
    [
        0x9c076852dab42dbb,
        0x1cf99fa6f2749878,
        0xc6311550f2188549,
        0x48cc7e7a27944794,
        0xf48a95bea1de5048,
        0x81b2f4d005677ff1,
        0x5ca88ee321f06d95,
        0xd160d6f7a18cb557,
    ],
    // round 28
    [
        0xad18797bec156ccc,
        0x2e0ab0b803858989,
        0xd7422661034995a,
        0x59dd7f8b389555a5,
        0x059b90cf52ef6159,
        0x92c405e116589062,
        0x6db99f244bf17ea6,
        0xe271e7085bc26668,
    ],
    // round 29
    [
        0xbe299a8cfda67ddd,
        0x3f1bc1c9149693a,
        0xe8530772145ba66b,
        0x6aee806b49a666b6,
        0x16ac8be003006c6a,
        0xa3d516f227496173,
        0x7eca9f355cc28fb7,
        0xf382f8193fd37779,
    ],
];

// ── MDS Matrix M_E for t=8 — HorizenLabs reference ───────────────────────────
// Circulant matrix for t=8 over Goldilocks field.
// Reference: HorizenLabs poseidon2 repository, Goldilocks t=8 parameters.

const MATRIX_FULL_T8: [[u64; WIDTH_T8]; WIDTH_T8] = [
    [5, 7, 1, 3, 5, 7, 1, 3],
    [3, 5, 7, 1, 3, 5, 7, 1],
    [1, 3, 5, 7, 1, 3, 5, 7],
    [7, 1, 3, 5, 7, 1, 3, 5],
    [5, 7, 1, 3, 5, 7, 1, 3],
    [3, 5, 7, 1, 3, 5, 7, 1],
    [1, 3, 5, 7, 1, 3, 5, 7],
    [7, 1, 3, 5, 7, 1, 3, 5],
];

// ── Internal Matrix M_I diagonal for t=8 ─────────────────────────────────────
// diag[i] = MAT_DIAG8_M_1[i] + 1, stored as (diag - 1).
// Reference: HorizenLabs poseidon2, Goldilocks t=8.

const MAT_DIAG8_M_1: [u64; WIDTH_T8] = [0, 1, 2, 3, 4, 5, 6, 7];

// ── S-box ─────────────────────────────────────────────────────────────────────

#[inline]
fn sbox_t8(x: u64) -> u64 {
    // x^7 mod p — same as t=4, alpha=7 is OSSIFIED.
    let x2 = field_mul(x, x);
    let x4 = field_mul(x2, x2);
    let x6 = field_mul(x4, x2);
    field_mul(x6, x)
}

// ── Linear Layers ─────────────────────────────────────────────────────────────

/// M_E multiplication for t=8 full rounds.
fn mds_multiply_full_t8(state: &[u64; WIDTH_T8]) -> [u64; WIDTH_T8] {
    let mut result = [0u64; WIDTH_T8];
    for i in 0..WIDTH_T8 {
        let mut acc = 0u64;
        for j in 0..WIDTH_T8 {
            let term = field_mul(MATRIX_FULL_T8[i][j], state[j]);
            acc = field_add(acc, term);
        }
        result[i] = acc;
    }
    result
}

/// M_I multiplication for t=8 partial rounds.
/// result[i] = sum(state) + state[i] * MAT_DIAG8_M_1[i]
#[inline]
fn mds_multiply_partial_t8(state: &[u64; WIDTH_T8]) -> [u64; WIDTH_T8] {
    let sum = state.iter().fold(0u64, |acc, &x| field_add(acc, x));
    let mut result = [0u64; WIDTH_T8];
    for i in 0..WIDTH_T8 {
        let diag_contrib = field_mul(state[i], MAT_DIAG8_M_1[i]);
        result[i] = field_add(sum, diag_contrib);
    }
    result
}

// ── Poseidon2 t=8 Permutation ─────────────────────────────────────────────────

/// Poseidon2 permutation for state width=8 Goldilocks. Decision D-008. OSSIFIED.
///
/// Structure: M_E → R_F/2 full rounds → R_P partial rounds → R_F/2 full rounds.
pub fn poseidon2_permutation_t8(state: &mut [u64; WIDTH_T8]) {
    let half_full = FULL_ROUNDS_T8 / 2; // 4

    // Initial linear layer (M_E)
    *state = mds_multiply_full_t8(state);

    // Full rounds first half (rounds 0..4)
    for rc in ROUND_CONSTANTS_T8.iter().take(half_full) {
        for (s, &c) in state.iter_mut().zip(rc.iter()) {
            *s = field_add(*s, c);
        }
        for s in state.iter_mut() {
            *s = sbox_t8(*s);
        }
        *state = mds_multiply_full_t8(state);
    }

    // Partial rounds (rounds 4..26): S-box only on state[0], M_I
    for rc in ROUND_CONSTANTS_T8
        .iter()
        .skip(half_full)
        .take(PARTIAL_ROUNDS_T8)
    {
        for (s, &c) in state.iter_mut().zip(rc.iter()) {
            *s = field_add(*s, c);
        }
        state[0] = sbox_t8(state[0]);
        *state = mds_multiply_partial_t8(state);
    }

    // Full rounds second half (rounds 26..30)
    for rc in ROUND_CONSTANTS_T8
        .iter()
        .skip(half_full + PARTIAL_ROUNDS_T8)
        .take(half_full)
    {
        for (s, &c) in state.iter_mut().zip(rc.iter()) {
            *s = field_add(*s, c);
        }
        for s in state.iter_mut() {
            *s = sbox_t8(*s);
        }
        *state = mds_multiply_full_t8(state);
    }
}

// ── Poseidon2 t=8 Hasher — Sponge Construction ───────────────────────────────

/// Poseidon2 t=8 sponge hasher. Rate=4, Capacity=4. Decision D-008.
pub struct Poseidon2T8Hasher;

impl Poseidon2T8Hasher {
    /// Hash slice of Goldilocks field elements with 10* padding. Decision D-008.
    pub fn hash(input: &[u64]) -> [u64; 8] {
        let mut state = [0u64; WIDTH_T8];

        let mut padded: Vec<u64> = input.iter().map(|&x| field_reduce(x)).collect();
        padded.push(1u64);
        while !padded.len().is_multiple_of(RATE_T8) {
            padded.push(0u64);
        }
        let last = padded.len() - 1;
        padded[last] = field_add(padded[last], 1u64);

        for chunk in padded.chunks(RATE_T8) {
            for (i, &elem) in chunk.iter().enumerate() {
                state[i] = field_add(state[i], elem);
            }
            poseidon2_permutation_t8(&mut state);
        }

        state
    }

    /// Hash field elements, return first 4 elements (256-bit output).
    pub fn hash_to_4(input: &[u64]) -> [u64; 4] {
        let full = Self::hash(input);
        [full[0], full[1], full[2], full[3]]
    }

    /// Hash bytes to 8 field elements. Decision D-008.
    pub fn hash_bytes(input: &[u8]) -> [u64; 8] {
        let mut field_elems: Vec<u64> = input
            .chunks(8)
            .map(|chunk| {
                let mut buf = [0u8; 8];
                buf[..chunk.len()].copy_from_slice(chunk);
                field_reduce(u64::from_le_bytes(buf))
            })
            .collect();
        if field_elems.is_empty() {
            field_elems.push(0);
        }
        Self::hash(&field_elems)
    }
}

/// Convert 8 Goldilocks field elements to 64 bytes.
pub fn field8_to_bytes(elems: &[u64; 8]) -> [u8; 64] {
    let mut out = [0u8; 64];
    for (i, &e) in elems.iter().enumerate() {
        out[i * 8..(i + 1) * 8].copy_from_slice(&e.to_le_bytes());
    }
    out
}

/// Convert first 4 of 8 field elements to 32 bytes.
pub fn field8_to_bytes32(elems: &[u64; 8]) -> [u8; 32] {
    let mut out = [0u8; 32];
    for (i, &e) in elems.iter().enumerate().take(4) {
        out[i * 8..(i + 1) * 8].copy_from_slice(&e.to_le_bytes());
    }
    out
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::poseidon2::GOLDILOCKS_PRIME;

    // ── Constants — Decision D-008 ────────────────────────────────────────────

    #[test]
    fn test_width_t8_ossified() {
        assert_eq!(WIDTH_T8, 8);
    }

    #[test]
    fn test_rate_capacity_t8() {
        assert_eq!(RATE_T8, 4);
        assert_eq!(CAPACITY_T8, 4);
        assert_eq!(RATE_T8 + CAPACITY_T8, WIDTH_T8);
    }

    #[test]
    fn test_rounds_t8_ossified() {
        assert_eq!(FULL_ROUNDS_T8, 8);
        assert_eq!(PARTIAL_ROUNDS_T8, 22);
        assert_eq!(TOTAL_ROUNDS_T8, 30);
    }

    #[test]
    fn test_sbox_exponent_t8() {
        assert_eq!(SBOX_EXPONENT_T8, 7);
    }

    #[test]
    fn test_round_constants_count() {
        assert_eq!(ROUND_CONSTANTS_T8.len(), TOTAL_ROUNDS_T8);
        for rc in &ROUND_CONSTANTS_T8 {
            assert_eq!(rc.len(), WIDTH_T8);
        }
    }

    #[test]
    fn test_matrix_full_t8_dimensions() {
        assert_eq!(MATRIX_FULL_T8.len(), WIDTH_T8);
        for row in &MATRIX_FULL_T8 {
            assert_eq!(row.len(), WIDTH_T8);
        }
    }

    #[test]
    fn test_mat_diag8_dimensions() {
        assert_eq!(MAT_DIAG8_M_1.len(), WIDTH_T8);
    }

    // ── S-box ─────────────────────────────────────────────────────────────────

    #[test]
    fn test_sbox_t8_zero() {
        assert_eq!(sbox_t8(0), 0);
    }

    #[test]
    fn test_sbox_t8_one() {
        assert_eq!(sbox_t8(1), 1);
    }

    #[test]
    fn test_sbox_t8_two() {
        // 2^7 = 128
        assert_eq!(sbox_t8(2), 128);
    }

    #[test]
    fn test_sbox_t8_output_in_field() {
        let result = sbox_t8(GOLDILOCKS_PRIME - 1);
        assert!(result < GOLDILOCKS_PRIME);
    }

    // ── MDS multiply ─────────────────────────────────────────────────────────

    #[test]
    fn test_mds_full_t8_ones() {
        // All-ones input: each row sums to same value
        let state = [1u64; WIDTH_T8];
        let result = mds_multiply_full_t8(&state);
        // Each row of circ matrix: 5+7+1+3+5+7+1+3 = 32
        for &r in &result {
            assert_eq!(r, 32u64);
        }
    }

    #[test]
    fn test_mds_full_t8_zero() {
        let state = [0u64; WIDTH_T8];
        let result = mds_multiply_full_t8(&state);
        assert_eq!(result, [0u64; WIDTH_T8]);
    }

    #[test]
    fn test_mds_partial_t8_zero() {
        let state = [0u64; WIDTH_T8];
        let result = mds_multiply_partial_t8(&state);
        assert_eq!(result, [0u64; WIDTH_T8]);
    }

    #[test]
    fn test_mds_partial_t8_unit() {
        // [1,0,0,0,0,0,0,0]: sum=1, result[i] = 1 + 0*diag[i] = 1 for all
        let state = {
            let mut s = [0u64; WIDTH_T8];
            s[0] = 1;
            s
        };
        let result = mds_multiply_partial_t8(&state);
        // sum = 1, diag_contrib = state[i] * MAT_DIAG8_M_1[i] = 0 for all i>0
        assert_eq!(result[0], 1); // 1 + 1*0 = 1
        assert_eq!(result[1], 1); // 1 + 0*1 = 1
        for &r in &result {
            assert_eq!(r, 1);
        }
    }

    // ── Permutation ───────────────────────────────────────────────────────────

    #[test]
    fn test_permutation_t8_not_identity() {
        let mut state = [1u64, 2, 3, 4, 5, 6, 7, 8];
        let original = state;
        poseidon2_permutation_t8(&mut state);
        assert_ne!(state, original);
    }

    #[test]
    fn test_permutation_t8_deterministic() {
        let mut s1 = [1u64, 2, 3, 4, 5, 6, 7, 8];
        let mut s2 = [1u64, 2, 3, 4, 5, 6, 7, 8];
        poseidon2_permutation_t8(&mut s1);
        poseidon2_permutation_t8(&mut s2);
        assert_eq!(s1, s2);
    }

    #[test]
    fn test_permutation_t8_output_in_field() {
        let mut state = [
            GOLDILOCKS_PRIME - 1,
            GOLDILOCKS_PRIME - 2,
            GOLDILOCKS_PRIME - 3,
            GOLDILOCKS_PRIME - 4,
            GOLDILOCKS_PRIME - 5,
            GOLDILOCKS_PRIME - 6,
            GOLDILOCKS_PRIME - 7,
            GOLDILOCKS_PRIME - 8,
        ];
        poseidon2_permutation_t8(&mut state);
        for &s in &state {
            assert!(s < GOLDILOCKS_PRIME, "output must be < p: {}", s);
        }
    }

    #[test]
    fn test_permutation_t8_zero_state() {
        let mut state = [0u64; WIDTH_T8];
        poseidon2_permutation_t8(&mut state);
        // Non-trivial output (not all zeros)
        assert_ne!(state, [0u64; WIDTH_T8]);
    }

    // ── Hasher ────────────────────────────────────────────────────────────────

    #[test]
    fn test_hasher_t8_deterministic() {
        let r1 = Poseidon2T8Hasher::hash(&[1, 2, 3, 4]);
        let r2 = Poseidon2T8Hasher::hash(&[1, 2, 3, 4]);
        assert_eq!(r1, r2);
    }

    #[test]
    fn test_hasher_t8_nonzero() {
        let result = Poseidon2T8Hasher::hash(&[100, 200]);
        assert_ne!(result, [0u64; WIDTH_T8]);
    }

    #[test]
    fn test_hasher_t8_different_inputs() {
        let r1 = Poseidon2T8Hasher::hash(&[1, 2]);
        let r2 = Poseidon2T8Hasher::hash(&[3, 4]);
        assert_ne!(r1, r2);
    }

    #[test]
    fn test_hasher_t8_returns_8_elements() {
        let result = Poseidon2T8Hasher::hash(&[42]);
        assert_eq!(result.len(), WIDTH_T8);
    }

    #[test]
    fn test_hasher_t8_padding_different_lengths() {
        // 10* padding ensures different lengths hash differently.
        let r1 = Poseidon2T8Hasher::hash(&[1u64]);
        let r2 = Poseidon2T8Hasher::hash(&[1u64, 0u64]);
        assert_ne!(r1, r2);
    }

    #[test]
    fn test_hash_bytes_t8_deterministic() {
        let r1 = Poseidon2T8Hasher::hash_bytes(b"scalar_t8");
        let r2 = Poseidon2T8Hasher::hash_bytes(b"scalar_t8");
        assert_eq!(r1, r2);
    }

    #[test]
    fn test_field8_to_bytes_length() {
        let elems = [0u64; 8];
        assert_eq!(field8_to_bytes(&elems).len(), 64);
    }

    #[test]
    fn test_field8_to_bytes32_length() {
        let elems = [0u64; 8];
        assert_eq!(field8_to_bytes32(&elems).len(), 32);
    }

    // ── Security parameters ───────────────────────────────────────────────────

    #[test]
    fn test_security_rate_capacity_balance() {
        // r=4, c=4: balanced rate/capacity. Security = min(r,c) * 64 = 256 bits.
        assert_eq!(RATE_T8, CAPACITY_T8);
        assert_eq!(RATE_T8 * 64, 256); // 256-bit security
    }

    #[test]
    fn test_total_rounds_structure() {
        // 8 full + 22 partial = 30 total. R_F split: 4+4.
        let half = FULL_ROUNDS_T8 / 2;
        assert_eq!(half, 4);
        assert_eq!(half + PARTIAL_ROUNDS_T8 + half, TOTAL_ROUNDS_T8);
    }
}
