[package]
name = "scalar-wallet-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
blake3 = "1.8.4"
zeroize = { version = "1.8", features = ["zeroize_derive"] }
argon2 = "0.5"
scalar-emission = { path = "../../core/scalar-emission" }
scalar-crypto    = { path = "../../core/scalar-crypto" }
