[package]
name = "scalar-node"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
# production: aktifkan Argon2id 4 GB RAM sesuai spec §2.1
# JANGAN aktifkan di Codespace — akan OOM crash
production = []

[dependencies]
scalar-crypto = { path = "../scalar-crypto" }
scalar-nullifier = { path = "../scalar-nullifier" }
scalar-stark-p3 = { path = "../scalar-stark-p3" }
postcard = { version = "1", features = ["alloc"] }
scalar-network = { path = "../scalar-network" }
tokio = { workspace = true, features = ["full"] }
anyhow.workspace = true
argon2 = "0.5.3"
serde_json = "1.0.149"
serde = { version = "1.0.228", features = ["derive"] }
scalar-consensus = { path = "../scalar-consensus" }
hex = "0.4"
blake3 = { workspace = true }
thiserror = { workspace = true }
scalar-emission = { path = "../scalar-emission" }
libp2p = { workspace = true, features = ["gossipsub", "kad", "macros", "noise", "tcp", "tokio", "yamux"] }
futures = "0.3"
tracing = "0.1"
tracing-subscriber = "0.3"