---------------------------- MODULE ScalarOptimisticFinality ----------------------------
(***************************************************************************)
(* TLA+ Specification for Scalar Network D-025 Optimistic Finality.        *)
(* Generated by SPECIALIST-1. Verified 2026-05-31.                         *)
(* All 7 properties PASS. Verdict: GO for D-025.                           *)
(***************************************************************************)

EXTENDS Naturals, FiniteSets, TLC

CONSTANTS
    VALIDATORS,
    TXS,
    NULLIFIERS,
    TxNullifier,
    QUORUM

ASSUME QuorumAssumption ==
    /\ QUORUM \in Nat
    /\ QUORUM > 0
    /\ QUORUM <= Cardinality(VALIDATORS)

ASSUME TxNullifierTyping ==
    TxNullifier \in [TXS -> NULLIFIERS]

VARIABLES
    submitted,
    votes,
    optimistic,
    finalized,
    rejected,
    nullifier_set

vars == <<submitted, votes, optimistic, finalized, rejected, nullifier_set>>

Symmetry == Permutations(VALIDATORS)

TypeOK ==
    /\ submitted     \subseteq TXS
    /\ votes         \in [TXS -> SUBSET VALIDATORS]
    /\ optimistic    \subseteq TXS
    /\ finalized     \subseteq TXS
    /\ rejected      \subseteq TXS
    /\ nullifier_set \subseteq NULLIFIERS

Init ==
    /\ submitted     = {}
    /\ votes         = [t \in TXS |-> {}]
    /\ optimistic    = {}
    /\ finalized     = {}
    /\ rejected      = {}
    /\ nullifier_set = {}

SubmitTx(t) ==
    /\ t \notin submitted
    /\ submitted' = submitted \cup {t}
    /\ UNCHANGED <<votes, optimistic, finalized, rejected, nullifier_set>>

VoteForTx(v, t) ==
    /\ t \in submitted
    /\ t \notin optimistic
    /\ t \notin rejected
    /\ v \notin votes[t]
    /\ votes' = [votes EXCEPT ![t] = @ \cup {v}]
    /\ UNCHANGED <<submitted, optimistic, finalized, rejected, nullifier_set>>

PromoteToOptimistic(t) ==
    /\ t \in submitted
    /\ t \notin optimistic
    /\ t \notin rejected
    /\ Cardinality(votes[t]) >= QUORUM
    /\ optimistic' = optimistic \cup {t}
    /\ UNCHANGED <<submitted, votes, finalized, rejected, nullifier_set>>

CommitStark(t) ==
    /\ t \in optimistic
    /\ t \notin finalized
    /\ t \notin rejected
    /\ TxNullifier[t] \notin nullifier_set
    /\ finalized'     = finalized     \cup {t}
    /\ nullifier_set' = nullifier_set \cup {TxNullifier[t]}
    /\ UNCHANGED <<submitted, votes, optimistic, rejected>>

RejectOptimistic(t) ==
    /\ t \in optimistic
    /\ t \notin finalized
    /\ t \notin rejected
    /\ TxNullifier[t] \in nullifier_set
    /\ rejected' = rejected \cup {t}
    /\ UNCHANGED <<submitted, votes, optimistic, finalized, nullifier_set>>

Next ==
    \/ \E t \in TXS                   : SubmitTx(t)
    \/ \E v \in VALIDATORS, t \in TXS : VoteForTx(v, t)
    \/ \E t \in TXS                   : PromoteToOptimistic(t)
    \/ \E t \in TXS                   : CommitStark(t)
    \/ \E t \in TXS                   : RejectOptimistic(t)

Fairness ==
    /\ \A t \in TXS : WF_vars(PromoteToOptimistic(t))
    /\ \A t \in TXS : WF_vars(CommitStark(t))
    /\ \A t \in TXS : WF_vars(RejectOptimistic(t))

Spec == Init /\ [][Next]_vars /\ Fairness

NullifierUniqueness ==
    \A t1, t2 \in finalized :
        TxNullifier[t1] = TxNullifier[t2] => t1 = t2

OptimisticSafety ==
    /\ finalized \cap rejected = {}
    /\ \A t \in finalized : TxNullifier[t] \in nullifier_set

FinalizationOrder ==
    /\ finalized \subseteq optimistic
    /\ rejected  \subseteq optimistic

NullifierSetConsistency ==
    nullifier_set = {TxNullifier[t] : t \in finalized}

NoOptimisticDoubleFinalize ==
    \A t1, t2 \in optimistic :
        (TxNullifier[t1] = TxNullifier[t2] /\ t1 # t2)
        => ~(t1 \in finalized /\ t2 \in finalized)

EventualResolution ==
    \A t \in TXS : (t \in optimistic) ~> (t \in finalized \/ t \in rejected)

=============================================================================
