[package]
name = "scalar-compliance"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
scalar-emission  = { path = "../scalar-emission" }
scalar-fees      = { path = "../scalar-fees" }
scalar-network   = { path = "../scalar-network" }
scalar-nullifier = { path = "../scalar-nullifier" }
scalar-wallet-core = { path = "../../client/scalar-wallet-core" }
