"""
Poseidon2 permutation — Goldilocks field, width=8.

impl#2 (independent re-implementation) for multi-client verification.
MAD §15.3, SCALAR-SECURITY §5.3.

Spec:    SCALAR-TECHNICAL §1.1 (OSSIFIED parameters)
RC src:  p3-goldilocks v0.5.3, GOLDILOCKS_POSEIDON2_RC_8_*
MDS:     p3-poseidon2 v0.5.3 apply_mat4 + mds_light_permutation (circulant)

NOTE: SCALAR-TECHNICAL §1.1 MDSMat4 description is for a DIFFERENT matrix
      than what Plonky3 actually uses. The authoritative source is
      p3-poseidon2/src/external.rs apply_mat4.
"""

# ── Goldilocks prime ──────────────────────────────────────────────────────────
P = (1 << 64) - (1 << 32) + 1  # 0xFFFFFFFF00000001

# ── Field arithmetic ──────────────────────────────────────────────────────────

def gl_add(a, b):
    return (a + b) % P

def gl_mul(a, b):
    return (a * b) % P

def gl_pow7(a):
    """S-box: x -> x^7 (alpha=7, OSSIFIED)."""
    a2 = gl_mul(a, a)
    a4 = gl_mul(a2, a2)
    return gl_mul(gl_mul(a4, a2), a)

# ── External MDS — apply_mat4 + mds_light_permutation ────────────────────────
# Source: p3-poseidon2 v0.5.3 external.rs
#
# apply_mat4 multiplies by the circulant matrix with first row [2,3,1,1]:
#   row 0: [2, 3, 1, 1]
#   row 1: [1, 2, 3, 1]
#   row 2: [1, 1, 2, 3]
#   row 3: [3, 1, 1, 2]
#
# mds_light_permutation for width-8:
#   1. Apply apply_mat4 to each group of 4 elements independently.
#   2. sums[k] = state[k] + state[k+4]  (sum across groups)
#   3. state[i] += sums[i % 4]

def _apply_mat4(s):
    """p3-poseidon2 apply_mat4 — circulant matrix [2,3,1,1]."""
    t01   = gl_add(s[0], s[1])
    t23   = gl_add(s[2], s[3])
    t0123 = gl_add(t01, t23)
    t01123 = gl_add(t0123, s[1])            # t0123 + x[1]
    t01233 = gl_add(t0123, s[3])            # t0123 + x[3]
    # Overwrite x[0] and x[2] after x[1] and x[3] (order matters in Rust)
    r3 = gl_add(t01233, gl_add(s[0], s[0])) # 3x0+x1+x2+2x3
    r1 = gl_add(t01123, gl_add(s[2], s[2])) # x0+2x1+3x2+x3
    r0 = gl_add(t01123, t01)                 # 2x0+3x1+x2+x3
    r2 = gl_add(t01233, t23)                 # x0+x1+2x2+3x3
    return [r0, r1, r2, r3]

def _external_mds_8(state):
    """mds_light_permutation(state, MDSMat4) for width=8."""
    # Step 1: apply apply_mat4 to each group of 4
    left  = _apply_mat4(state[0:4])
    right = _apply_mat4(state[4:8])
    s = left + right
    # Step 2: sums[k] = state[k] + state[k+4]
    sums = [gl_add(s[k], s[k + 4]) for k in range(4)]
    # Step 3: state[i] += sums[i % 4]
    return [gl_add(s[i], sums[i % 4]) for i in range(8)]

# ── Internal MDS — MATRIX_DIAG_8_GOLDILOCKS (OSSIFIED) ───────────────────────
# Source: p3-goldilocks v0.5.3
# state[i] = state[i] * DIAG[i] + sum(state)

_DIAG_8 = [
    0xFFFFFFFEFFFFFFFF,  # -2
    0x0000000000000001,  #  1
    0x0000000000000002,  #  2
    0x7FFFFFFF80000001,  #  1/2
    0x0000000000000003,  #  3
    0x7FFFFFFF80000000,  # -1/2
    0xFFFFFFFEFFFFFFFE,  # -3
    0xFFFFFFFEFFFFFFFD,  # -4
]

def _internal_mds_8(state):
    """Internal MDS: state[i] = state[i] * DIAG[i] + sum(state)."""
    total = 0
    for x in state:
        total = gl_add(total, x)
    return [gl_add(gl_mul(state[i], _DIAG_8[i]), total) for i in range(8)]

# ── Round Constants (OSSIFIED) ────────────────────────────────────────────────
# p3-goldilocks v0.5.3, GOLDILOCKS_POSEIDON2_RC_8_EXTERNAL_INITIAL/FINAL/INTERNAL
# Generated by Grain LFSR: field_type=1, alpha=7, n=64, t=8, R_F=8, R_P=22

RC_EXT_INIT = [
    [0xdd5743e7f2a5a5d9,0xcb3a864e58ada44b,0xffa2449ed32f8cdc,0x42025f65d6bd13ee,
     0x7889175e25506323,0x34b98bb03d24b737,0xbdcc535ecc4faa2a,0x5b20ad869fc0d033],
    [0xf1dda5b9259dfcb4,0x27515210be112d59,0x4227d1718c766c3f,0x26d333161a5bd794,
     0x49b938957bf4b026,0x4a56b5938b213669,0x1120426b48c8353d,0x6b323c3f10a56cad],
    [0xce57d6245ddca6b2,0xb1fc8d402bba1eb1,0xb5c5096ca959bd04,0x6db55cd306d31f7f,
     0xc49d293a81cb9641,0x1ce55a4fe979719f,0xa92e60a9d178a4d1,0x002cc64973bcfd8c],
    [0xcea721cce82fb11b,0xe5b55eb8098ece81,0x4e30525c6f1ddd66,0x43c6702827070987,
     0xaca68430a7b5762a,0x3674238634df9c93,0x88cee1c825e33433,0xde99ae8d74b57176],
]

RC_EXT_FINAL = [
    [0x014ef1197d341346,0x9725e20825d07394,0xfdb25aef2c5bae3b,0xbe5402dc598c971e,
     0x93a5711f04cdca3d,0xc45a9a5b2f8fb97b,0xfe8946a924933545,0x2af997a27369091c],
    [0xaa62c88e0b294011,0x058eb9d810ce9f74,0xb3cb23eced349ae4,0xa3648177a77b4a84,
     0x43153d905992d95d,0xf4e2a97cda44aa4b,0x5baa2702b908682f,0x082923bdf4f750d1],
    [0x98ae09a325893803,0xf8a6475077968838,0xceb0735bf00b2c5f,0x0a1a5d953888e072,
     0x2fcb190489f94475,0xb5be06270dec69fc,0x739cb934b09acf8b,0x537750b75ec7f25b],
    [0xe9dd318bae1f3961,0xf7462137299efe1a,0xb1f6b8eee9adb940,0xbdebcc8a809dfe6b,
     0x40fc1f791b178113,0x3ac1c3362d014864,0x9a016184bdb8aeba,0x95f2394459fbc25e],
]

RC_INT = [
    0x488897d85ff51f56,0x1140737ccb162218,0xa7eeb9215866ed35,0x9bd2976fee49fcc9,
    0xc0c8f0de580a3fcc,0x4fb2dae6ee8fc793,0x343a89f35f37395b,0x223b525a77ca72c8,
    0x56ccb62574aaa918,0xc4d507d8027af9ed,0xa080673cf0b7e95c,0xf0184884eb70dcf8,
    0x044f10b0cb3d5c69,0xe9e3f7993938f186,0x1b761c80e772f459,0x606cec607a1b5fac,
    0x14a0c2e1d45f03cd,0x4eace8855398574f,0xf905ca7103eff3e6,0xf8c8f8d20862c059,
    0xb524fe8bdd678e5a,0xfbb7865901a1ec41,
]

# ── Permutation ───────────────────────────────────────────────────────────────

def poseidon2_permute(state):
    """
    Poseidon2 permutation: Goldilocks, width=8, alpha=7, R_F=8, R_P=22.

    Sequence (p3-poseidon2 + p3-poseidon2-air):
      1. external_linear_layer (mds_light_permutation — initial)
      2. 4 beginning full rounds: AddRC -> SBox(all) -> external_linear_layer
      3. 22 partial rounds: AddRC[0] -> SBox[0] -> internal_linear_layer
      4. 4 ending full rounds: AddRC -> SBox(all) -> external_linear_layer
    """
    s = list(state)

    # 1. Initial external linear layer
    s = _external_mds_8(s)

    # 2. Beginning full rounds
    for rc in RC_EXT_INIT:
        s = [gl_add(s[i], rc[i]) for i in range(8)]  # AddRC
        s = [gl_pow7(x) for x in s]                   # SBox
        s = _external_mds_8(s)                        # external_linear_layer

    # 3. Partial rounds
    for rc in RC_INT:
        s[0] = gl_add(s[0], rc)   # AddRC[0]
        s[0] = gl_pow7(s[0])      # SBox[0]
        s = _internal_mds_8(s)    # internal_linear_layer

    # 4. Ending full rounds
    for rc in RC_EXT_FINAL:
        s = [gl_add(s[i], rc[i]) for i in range(8)]  # AddRC
        s = [gl_pow7(x) for x in s]                   # SBox
        s = _external_mds_8(s)                        # external_linear_layer

    return s
