//! scalar-stark-p3-verify — Independent second STARK verifier. Spec §15.3, A-R7.
//!
//! Re-implements Transfer Circuit AIR (CD/CE/CG + range proofs) and
//! Mint Circuit AIR independently from scalar-stark-p3.
//! Proofs generated by scalar-stark-p3 MUST verify successfully here.
//!
//! Spec §15.3: "Multi-client STARK: dua implementasi independen harus
//! menghasilkan proof yang saling dapat diverifikasi."
//!
//! Independence: AIR constraint definitions are written from scratch
//! against the spec (§4.3, §5.2), not copy-pasted from scalar-stark-p3.
//! Both use the same OSSIFIED FRI params and Goldilocks field.

extern crate alloc;

pub mod transfer_air_v2;
pub mod mint_air_v2;
pub mod verify;

pub use verify::{
    verify_transfer_independent, verify_mint_independent, IndependentVerifyError,
};
