//! Transfer Circuit AIR — Independent second implementation. Spec §15.3, A-R7.
//!
//! Re-implements constraint groups CD, CE, CG independently from
//! scalar-stark-p3/transfer_air_p3.rs. Written from spec §4.3, §9.1, D-012.
//!
//! Constraints verified (identical to primary, independently coded):
//!   CD  — Value conservation: sum_inputs == sum_outputs + fee
//!   CD  — Fee floor: fee >= 40 sSCL via 52-bit decomposition (D-012)
//!   CE  — Output non-zero
//!   CG  — Crypto version == 0x01
//!   CG  — Timestamp window via 21-bit ts_slack decomposition (D-012)
//!   CB  — Membership verified flag
//!   CC  — Non-membership verified flag
//!   INV-4.6 — Single UTXO source
//!   A-R9 — Cross-binding commitment/nullifier hashes
//!
//! Trace layout MUST match scalar-stark-p3 exactly (OSSIFIED width=96).

use p3_air::{Air, AirBuilder, BaseAir, WindowAccess};
use p3_field::PrimeCharacteristicRing;
use p3_goldilocks::Goldilocks;
use p3_matrix::dense::RowMajorMatrix;

// ── OSSIFIED constants — must match scalar-stark-p3 exactly ──────────────────
// These are re-stated independently (not imported) to verify consistency.

/// Trace width. OSSIFIED — must equal scalar-stark-p3::TRANSFER_TRACE_WIDTH.
pub const TRANSFER_TRACE_WIDTH_V2: usize = 96;

// Column indices — re-stated from spec §4.3 trace layout, not imported.
const COL_FEE: usize = 0;
const COL_SUM_IN: usize = 1;
const COL_SUM_OUT: usize = 2;
const COL_VERSION: usize = 3;
const COL_ENTRY_TS_LO: usize = 4;
const COL_ENTRY_TS_HI: usize = 5;
const COL_CURRENT_TS_LO: usize = 6;
const COL_CURRENT_TS_HI: usize = 7;
const COL_CB_VERIFIED: usize = 8;
const COL_CC_VERIFIED: usize = 9;
const COL_OUTPUT_NONZERO: usize = 10;
const COL_SINGLE_SOURCE: usize = 11;
// 12..19: A-R9 cross-binding (commitment_hash[4] + nullifier_hash[4])
const COL_FEE_ABOVE_FLOOR: usize = 20;
const COL_TS_DELTA: usize = 21;
const COL_TS_SLACK: usize = 22;
const COL_FEE_BIT_START: usize = 23;
const FEE_BIT_COUNT: usize = 52;
const COL_TS_SLACK_BIT_START: usize = 75;
const TS_SLACK_BIT_COUNT: usize = 21;

/// Fee floor in sSCL. OSSIFIED — spec §9.1.
const FEE_FLOOR_SSCL: u64 = 40;
/// T_MAX_WAIT in ms. OSSIFIED — spec §4.3 CG.
const T_MAX_WAIT_MS: u64 = 30 * 60 * 1_000;
/// Valid crypto version. OSSIFIED — spec §4.3 CG.
const VALID_CRYPTO_VERSION: u64 = 0x01;

// ── TransferAirV2 — independent re-implementation ────────────────────────────

/// Independent second implementation of Transfer Circuit AIR. Spec §15.3.
///
/// Constraint logic written from spec §4.3, not copied from scalar-stark-p3.
/// Must accept proofs generated by scalar-stark-p3::TransferAirP3.
#[derive(Clone, Debug)]
pub struct TransferAirV2;

impl<F: PrimeCharacteristicRing + Sync> BaseAir<F> for TransferAirV2 {
    fn width(&self) -> usize {
        TRANSFER_TRACE_WIDTH_V2
    }

    fn main_next_row_columns(&self) -> Vec<usize> {
        // Single-row AIR — matches TransferAirP3. Spec §15.3: shape must be identical.
        vec![]
    }
    // num_public_values() intentionally NOT overridden → default = 0.
    // TransferAirP3 also uses default = 0. Public values (44 elem) are passed
    // via transcript, not encoded in AirLayout. Spec §15.3.
}

impl<AB: AirBuilder> Air<AB> for TransferAirV2 {
    fn eval(&self, builder: &mut AB) {
        let main = builder.main();
        let local: &[AB::Var] = main.current_slice();

        let fee = local[COL_FEE];
        let sum_in = local[COL_SUM_IN];
        let sum_out = local[COL_SUM_OUT];
        let version = local[COL_VERSION];
        let entry_lo = local[COL_ENTRY_TS_LO];
        let entry_hi = local[COL_ENTRY_TS_HI];
        let current_lo = local[COL_CURRENT_TS_LO];
        let current_hi = local[COL_CURRENT_TS_HI];
        let cb_ok = local[COL_CB_VERIFIED];
        let cc_ok = local[COL_CC_VERIFIED];
        let out_nz = local[COL_OUTPUT_NONZERO];
        let single_src = local[COL_SINGLE_SOURCE];
        let fee_above_floor = local[COL_FEE_ABOVE_FLOOR];
        let ts_delta = local[COL_TS_DELTA];
        let ts_slack = local[COL_TS_SLACK];

        // ── CD: Value conservation ────────────────────────────────────────────
        // sum_inputs == sum_outputs + fee → sum_in - sum_out - fee == 0
        builder.assert_zero(sum_in - sum_out - fee);

        // ── CD: Fee floor — 52-bit range proof (D-012) ───────────────────────
        // fee == FEE_FLOOR + fee_above_floor
        let fee_floor = AB::F::from_u64(FEE_FLOOR_SSCL);
        builder.assert_eq(fee.into(), fee_above_floor.into() + fee_floor);
        // fee_above_floor bit decomposition
        {
            let mut reconstructed: AB::Expr = AB::F::ZERO.into();
            let mut power: AB::Expr = AB::F::ONE.into();
            for i in 0..FEE_BIT_COUNT {
                let bit = local[COL_FEE_BIT_START + i];
                builder.assert_zero(bit * (bit - AB::F::ONE));
                reconstructed += bit * power.clone();
                power *= AB::F::from_u64(2u64);
            }
            builder.assert_eq(fee_above_floor.into(), reconstructed);
        }

        // ── CG: Crypto version ────────────────────────────────────────────────
        builder.assert_eq(version.into(), AB::F::from_u64(VALID_CRYPTO_VERSION));

        // ── CG: Timestamp window — 21-bit ts_slack range proof (D-012) ───────
        let two32 = AB::F::from_u64(1u64 << 32);
        let entry_ts: AB::Expr = entry_lo.into() + entry_hi * two32.clone();
        let current_ts: AB::Expr = current_lo.into() + current_hi * two32;
        // ts_delta == current_ts - entry_ts
        builder.assert_eq(ts_delta.into(), current_ts - entry_ts);
        // ts_delta + ts_slack == T_MAX_WAIT_MS
        builder.assert_eq(
            ts_delta.into() + ts_slack.into(),
            AB::F::from_u64(T_MAX_WAIT_MS),
        );
        // ts_slack bit decomposition (proves ts_slack in [0, 2^21))
        {
            let mut reconstructed: AB::Expr = AB::F::ZERO.into();
            let mut power: AB::Expr = AB::F::ONE.into();
            for i in 0..TS_SLACK_BIT_COUNT {
                let bit = local[COL_TS_SLACK_BIT_START + i];
                builder.assert_zero(bit * (bit - AB::F::ONE));
                reconstructed += bit * power.clone();
                power *= AB::F::from_u64(2u64);
            }
            builder.assert_eq(ts_slack.into(), reconstructed);
        }

        // ── CB: Membership verified ───────────────────────────────────────────
        builder.assert_zero(cb_ok * (cb_ok - AB::F::ONE));
        builder.assert_one(cb_ok);

        // ── CC: Non-membership verified ───────────────────────────────────────
        builder.assert_zero(cc_ok * (cc_ok - AB::F::ONE));
        builder.assert_one(cc_ok);

        // ── CE: Output non-zero ───────────────────────────────────────────────
        builder.assert_zero(out_nz * (out_nz - AB::F::ONE));
        builder.assert_one(out_nz);

        // ── INV-4.6: Single UTXO source ──────────────────────────────────────
        builder.assert_zero(single_src * (single_src - AB::F::ONE));
        builder.assert_one(single_src);
    }
}

/// Build trace for V2 verifier — identical layout to scalar-stark-p3.
/// Used in cross-verification tests. Spec §15.3.
// Each argument maps directly to a Transfer circuit column (MAD §5.2).
// Argument count is protocol-mandated, not a design choice.
#[allow(clippy::too_many_arguments)]
pub fn build_transfer_trace_v2(
    fee: u64,
    sum_in: u64,
    sum_out: u64,
    crypto_version: u8,
    entry_ts_ms: u64,
    current_ts_ms: u64,
    cb_ok: bool,
    cc_ok: bool,
    output_nonzero: bool,
    single_source: bool,
    commitment_hash: [u64; 4],
    nullifier_hash: [u64; 4],
    num_rows: usize,
) -> RowMajorMatrix<Goldilocks> {
    assert!(num_rows.is_power_of_two());

    let fee_above_floor = fee.saturating_sub(FEE_FLOOR_SSCL);
    let ts_delta = current_ts_ms.saturating_sub(entry_ts_ms);
    let ts_slack = T_MAX_WAIT_MS.saturating_sub(ts_delta);

    let mut fee_bits = [0u64; FEE_BIT_COUNT];
    for (i, b) in fee_bits.iter_mut().enumerate() {
        *b = (fee_above_floor >> i) & 1;
    }
    let mut ts_bits = [0u64; TS_SLACK_BIT_COUNT];
    for (i, b) in ts_bits.iter_mut().enumerate() {
        *b = (ts_slack >> i) & 1;
    }

    let mut row = [Goldilocks::new(0u64); TRANSFER_TRACE_WIDTH_V2];
    row[COL_FEE] = Goldilocks::new(fee);
    row[COL_SUM_IN] = Goldilocks::new(sum_in);
    row[COL_SUM_OUT] = Goldilocks::new(sum_out);
    row[COL_VERSION] = Goldilocks::new(crypto_version as u64);
    row[COL_ENTRY_TS_LO] = Goldilocks::new(entry_ts_ms & 0xFFFF_FFFF);
    row[COL_ENTRY_TS_HI] = Goldilocks::new(entry_ts_ms >> 32);
    row[COL_CURRENT_TS_LO] = Goldilocks::new(current_ts_ms & 0xFFFF_FFFF);
    row[COL_CURRENT_TS_HI] = Goldilocks::new(current_ts_ms >> 32);
    row[COL_CB_VERIFIED] = Goldilocks::new(cb_ok as u64);
    row[COL_CC_VERIFIED] = Goldilocks::new(cc_ok as u64);
    row[COL_OUTPUT_NONZERO] = Goldilocks::new(output_nonzero as u64);
    row[COL_SINGLE_SOURCE] = Goldilocks::new(single_source as u64);
    row[12] = Goldilocks::new(commitment_hash[0]);
    row[13] = Goldilocks::new(commitment_hash[1]);
    row[14] = Goldilocks::new(commitment_hash[2]);
    row[15] = Goldilocks::new(commitment_hash[3]);
    row[16] = Goldilocks::new(nullifier_hash[0]);
    row[17] = Goldilocks::new(nullifier_hash[1]);
    row[18] = Goldilocks::new(nullifier_hash[2]);
    row[19] = Goldilocks::new(nullifier_hash[3]);
    row[COL_FEE_ABOVE_FLOOR] = Goldilocks::new(fee_above_floor);
    row[COL_TS_DELTA] = Goldilocks::new(ts_delta);
    row[COL_TS_SLACK] = Goldilocks::new(ts_slack);
    for i in 0..FEE_BIT_COUNT {
        row[COL_FEE_BIT_START + i] = Goldilocks::new(fee_bits[i]);
    }
    for i in 0..TS_SLACK_BIT_COUNT {
        row[COL_TS_SLACK_BIT_START + i] = Goldilocks::new(ts_bits[i]);
    }

    let mut vals = vec![Goldilocks::new(0); num_rows * TRANSFER_TRACE_WIDTH_V2];
    for r in 0..num_rows {
        for c in 0..TRANSFER_TRACE_WIDTH_V2 {
            vals[r * TRANSFER_TRACE_WIDTH_V2 + c] = row[c];
        }
    }
    RowMajorMatrix::new(vals, TRANSFER_TRACE_WIDTH_V2)
}
