"""
Milestone-1: Poseidon2 cross-check — impl#2 (Python) vs impl#1 (Rust).

Test oracle: verifier-py/tests/vectors/poseidon2_vectors.json
Generated by: cargo run -p test-vector-gen
[SCALAR-SECURITY §5.3 Tier 2]
"""
import json
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from scalar_verifier.poseidon2 import poseidon2_permute_t8, poseidon2_hash_chained, poseidon2_hash_to_4

VECTORS_PATH = os.path.join(os.path.dirname(__file__), 'vectors', 'poseidon2_vectors.json')

def run_tests():
    with open(VECTORS_PATH) as f:
        data = json.load(f)

    vectors = data['vectors']
    passed = 0
    failed = 0

    for v in vectors:
        primitive = v['primitive']
        inp = v['input']
        expected = v['output']
        note = v.get('note', '')

        if primitive == 'poseidon2_permute_t8':
            got = poseidon2_permute_t8(inp)
        elif primitive == 'poseidon2_hash_chained':
            got = poseidon2_hash_chained(inp)
        elif primitive == 'poseidon2_hash_to_4':
            got = poseidon2_hash_to_4(inp)  # single permutation D-010
        else:
            print(f"  SKIP unknown primitive: {primitive}")
            continue

        if got == expected:
            print(f"  PASS [{primitive}] {note}")
            passed += 1
        else:
            print(f"  FAIL [{primitive}] {note}")
            print(f"    input:    {inp}")
            print(f"    expected: {expected}")
            print(f"    got:      {got}")
            # Show first differing element
            for i, (e, g) in enumerate(zip(expected, got)):
                if e != g:
                    print(f"    first diff at [{i}]: expected={e:#018x} got={g:#018x}")
                    break
            failed += 1

    print(f"\nResult: {passed} passed, {failed} failed / {passed+failed} total")
    return failed == 0

if __name__ == '__main__':
    print("=== Milestone-1: Poseidon2 cross-check impl#2 (Python) vs impl#1 (Rust) ===")
    print(f"Source: {VECTORS_PATH}")
    print()
    ok = run_tests()
    sys.exit(0 if ok else 1)
